// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// getUpAndInPrice
double getUpAndInPrice(int nInt, double strike, double spot, double vol, double r, double expiry, double barrier, int nReps, char optionType);
RcppExport SEXP _OptionPricing_getUpAndInPrice(SEXP nIntSEXP, SEXP strikeSEXP, SEXP spotSEXP, SEXP volSEXP, SEXP rSEXP, SEXP expirySEXP, SEXP barrierSEXP, SEXP nRepsSEXP, SEXP optionTypeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type nInt(nIntSEXP);
    Rcpp::traits::input_parameter< double >::type strike(strikeSEXP);
    Rcpp::traits::input_parameter< double >::type spot(spotSEXP);
    Rcpp::traits::input_parameter< double >::type vol(volSEXP);
    Rcpp::traits::input_parameter< double >::type r(rSEXP);
    Rcpp::traits::input_parameter< double >::type expiry(expirySEXP);
    Rcpp::traits::input_parameter< double >::type barrier(barrierSEXP);
    Rcpp::traits::input_parameter< int >::type nReps(nRepsSEXP);
    Rcpp::traits::input_parameter< char >::type optionType(optionTypeSEXP);
    rcpp_result_gen = Rcpp::wrap(getUpAndInPrice(nInt, strike, spot, vol, r, expiry, barrier, nReps, optionType));
    return rcpp_result_gen;
END_RCPP
}
// getEuropeanPrice
double getEuropeanPrice(int nInt, double strike, double spot, double vol, double r, double expiry, int nReps, char optionType);
RcppExport SEXP _OptionPricing_getEuropeanPrice(SEXP nIntSEXP, SEXP strikeSEXP, SEXP spotSEXP, SEXP volSEXP, SEXP rSEXP, SEXP expirySEXP, SEXP nRepsSEXP, SEXP optionTypeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type nInt(nIntSEXP);
    Rcpp::traits::input_parameter< double >::type strike(strikeSEXP);
    Rcpp::traits::input_parameter< double >::type spot(spotSEXP);
    Rcpp::traits::input_parameter< double >::type vol(volSEXP);
    Rcpp::traits::input_parameter< double >::type r(rSEXP);
    Rcpp::traits::input_parameter< double >::type expiry(expirySEXP);
    Rcpp::traits::input_parameter< int >::type nReps(nRepsSEXP);
    Rcpp::traits::input_parameter< char >::type optionType(optionTypeSEXP);
    rcpp_result_gen = Rcpp::wrap(getEuropeanPrice(nInt, strike, spot, vol, r, expiry, nReps, optionType));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_hello_world
List rcpp_hello_world();
RcppExport SEXP _OptionPricing_rcpp_hello_world() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_hello_world());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_OptionPricing_getUpAndInPrice", (DL_FUNC) &_OptionPricing_getUpAndInPrice, 9},
    {"_OptionPricing_getEuropeanPrice", (DL_FUNC) &_OptionPricing_getEuropeanPrice, 8},
    {"_OptionPricing_rcpp_hello_world", (DL_FUNC) &_OptionPricing_rcpp_hello_world, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_OptionPricing(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
