# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getUpAndInPrice <- function(nInt, strike, spot, vol, r, expiry, barrier, nReps, optionType) {
    .Call(`_OptionPricing_getUpAndInPrice`, nInt, strike, spot, vol, r, expiry, barrier, nReps, optionType)
}

getEuropeanPrice <- function(nInt, strike, spot, vol, r, expiry, nReps, optionType) {
    .Call(`_OptionPricing_getEuropeanPrice`, nInt, strike, spot, vol, r, expiry, nReps, optionType)
}

rcpp_hello_world <- function() {
    .Call(`_OptionPricing_rcpp_hello_world`)
}

